//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitMTL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransitMTL.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string AddToFavs {
            get {
                return ResourceManager.GetString("AddToFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add Stop Number: .
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Stop Code.
        /// </summary>
        public static string BusStopCode {
            get {
                return ResourceManager.GetString("BusStopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Stop .
        /// </summary>
        public static string BusStopSpace {
            get {
                return ResourceManager.GetString("BusStopSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Bus Line .
        /// </summary>
        public static string CommaBusLineSpace {
            get {
                return ResourceManager.GetString("CommaBusLineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner.
        /// </summary>
        public static string Corner {
            get {
                return ResourceManager.GetString("Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete From Favorites.
        /// </summary>
        public static string DeleteFromFavs {
            get {
                return ResourceManager.GetString("DeleteFromFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Stop Code Here.
        /// </summary>
        public static string EnterStopCodeHere {
            get {
                return ResourceManager.GetString("EnterStopCodeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Added.
        /// </summary>
        public static string FavAdded {
            get {
                return ResourceManager.GetString("FavAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Added.
        /// </summary>
        public static string FavoriteAdded {
            get {
                return ResourceManager.GetString("FavoriteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Deleted.
        /// </summary>
        public static string FavoriteDeleted {
            get {
                return ResourceManager.GetString("FavoriteDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite not Added.
        /// </summary>
        public static string FavoriteNotAdded {
            get {
                return ResourceManager.GetString("FavoriteNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a stop to favorites enter the Bus Stop Code of your choice in the &quot;Stop Code&quot; Section and Long Press (Press and Hold) a bus line to save to Favorites. Long Press a favorite to remove it..
        /// </summary>
        public static string FavoritesCaption {
            get {
                return ResourceManager.GetString("FavoritesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been removed from favorites..
        /// </summary>
        public static string HasBeenRemovedFromFavs {
            get {
                return ResourceManager.GetString("HasBeenRemovedFromFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been saved to Favorites..
        /// </summary>
        public static string HasBeenSavedToFavs {
            get {
                return ResourceManager.GetString("HasBeenSavedToFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is already in Favorites..
        /// </summary>
        public static string IsAlreadyInFavorites {
            get {
                return ResourceManager.GetString("IsAlreadyInFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Passing Times.
        /// </summary>
        public static string NextPassingTimes {
            get {
                return ResourceManager.GetString("NextPassingTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Code.
        /// </summary>
        public static string StopCode {
            get {
                return ResourceManager.GetString("StopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Listing.
        /// </summary>
        public static string StopListingTitle {
            get {
                return ResourceManager.GetString("StopListingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Number.
        /// </summary>
        public static string StopNumber {
            get {
                return ResourceManager.GetString("StopNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add to Favorites.
        /// </summary>
        public static string TapForFav {
            get {
                return ResourceManager.GetString("TapForFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error has occured. Please ensure you have an active internet connection..
        /// </summary>
        public static string ThisAppRequiresInternetAccess {
            get {
                return ResourceManager.GetString("ThisAppRequiresInternetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to favorites?.
        /// </summary>
        public static string ToFavs {
            get {
                return ResourceManager.GetString("ToFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
    }
}
